basic_auth:
  enabled: false
redis:
  socket: /tmp/redis.sock
chart:
  cpu:
    color: '#D2691E'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
queues:
  time: pimon_time
  cpu:  pimon_cpu
  mem:  pimon_mem
  swap: pimon_swap
stats_collector:
  daemonize: false
  pid_dir : pids
  log_dir : log
  number_of_stats: 6
  time_period_in_min: 10
