basic_auth:
  enabled: false
redis:
  socket: /tmp/redis.sock
chart:
  cpu:
    color: '#D2691E'
  disk:
    color: '#CDC673'
  mem:
    color: '#87CEFA'
  temp:
    color: '#FF9B04'
  swap:
    color: '#3CB371'
queues:
  time: pimon_time
  cpu:  pimon_cpu
  disk: pimon_disk
  mem:  pimon_mem
  swap: pimon_swap
  temp: pimon_temp
stats_collector:
  number_of_stats: 6
  time_period_in_min: 1
