basic_auth:
  enabled: true
  username: changed_on_deploy
  password: changed_on_deploy
redis:
  socket: /tmp/redis.sock
chart:
  cpu:
    color: '#D2691E'
  disk:
    color: '#CDC673'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
queues:
  time: pimon_time
  cpu:  pimon_cpu
  disk: pimon_disk
  mem:  pimon_mem
  swap: pimon_swap
stats_collector:
  number_of_stats: 12
  time_period_in_min: 5
