basic_auth:
  enabled: true
  username: changed_on_deploy
  password: changed_on_deploy
redis:
  socket: /tmp/redis.sock
chart:
  cpu:
    color: '#D2691E'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
stats:
  slices: 6
  time_period_in_min: 10
