basic_auth:
  enabled: true
  username: changed_on_deploy
  password: changed_on_deploy
redis:
  socket: /tmp/redis.sock
chart:
  cpu:
    color: '#D2691E'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
queues:
  time: pimon_time
  cpu:  pimon_cpu
  mem:  pimon_mem
  swap: pimon_swap
stats_collector:
  daemonize: true
  pid_dir : /home/pi/app/pimon/shared/pids/
  log_dir : /home/pi/app/pimon/shared/log/
  number_of_stats: 6
  time_period_in_min: 10
