chart:
  cpu:
    color: '#D2691E'
  disk:
    color: '#CDC673'
  mem:
    color: '#87CEFA'
  temp:
    color: '#FF9B04'
  swap:
    color: '#3CB371'
hostname: 'test_hostname'
stats_collector:
  number_of_stats: 6
  time_period_in_min: 10
