basic_auth:
  enabled: true
  username: pimon
  password: pimon
redis:
  socket: /thou/shalt/not/use/redis/on/test/environment
chart:
  cpu:
    color: '#D2691E'
  disk:
    color: '#CDC673'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
queues:
  time: pimon_time
  cpu:  pimon_cpu
  disk: pimon_disk
  mem:  pimon_mem
  swap: pimon_swap
stats_collector:
  number_of_stats: 6
  time_period_in_min: 10
