basic_auth:
  enabled: true
  username: pimon
  password: pimon
redis:
  socket: /thou/shalt/not/use/redis/on/test/environment
chart:
  cpu:
    color: '#D2691E'
  mem:
    color: '#87CEFA'
  swap:
    color: '#3CB371'
stats:
  slices: 6
  time_period_in_min: 10
